// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Our Philosophy"
          quote="Mister Exteriors isn't about pressure washing. It's about an unwavering commitment to the preservation and perfection of your home's exterior presentation."
          author="The Mister Exteriors Team"
          role="Premium Home Care Specialists"
          imageSrc="https://storage.googleapis.com/webild/users/user_3HGof9QZxBPIQg7h8T53jziZ9o1/uploaded-1785937608634-rc2blac9.png"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
