// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Join Now"
          text="Apply for the Home Care Club. Secure your home’s prestige with our Unrelenting Standard™."
          primaryButton={{
            text: "Apply for Membership",
            href: "#",
          }}
          secondaryButton={{
            text: "Call Now: (954) 555-0199",
            href: "tel:9545550199",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
