// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import Apply NowCta from '@/components/sections/contact/Apply NowCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function Apply NowSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <Apply NowCta
          tag="Apply Now"
          text="Apply for the Home Care Club and never worry about your home's exterior again."
          primaryButton={{
            text: "Apply Now",
            href: "https://app.youform.com/forms/conyhf2h",
          }}
          secondaryButton={{
            text: "Call now: (954) 226-9454",
            href: "tel:+19542269454",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
