// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Frequently Asked Questions"
          description="Everything you need to know about our exclusive Home Care Club."
          items={[
            {
              question: "What is the 32-Point Unrelenting Standard™?",
              answer: "It is our proprietary checklist covering every inch of your exterior to ensure zero oversight.",
            },
            {
              question: "What if my home isn't perfectly maintained?",
              answer: "We guarantee our work. If it drops below standard, we restore it at no cost.",
            },
            {
              question: "How do I become a member?",
              answer: "Simply apply through the site. We review applications for compatibility with our service standard.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/luxury-travel-full-shot-woman_23-2149204471.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
