// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesArrowCards
          tag="How it works"
          title="Home Care Club"
          description="Exterior care without the hassle"
          items={[
            {
              title: "Restoration",
              tags: [
                "Deep Clean",
                "Safe",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-city-building-shadows_23-2149283297.jpg",
            },
            {
              title: "Preventative Care",
              tags: [
                "Precision",
                "Clear",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/metal-profiles-drywall-laid-floor-against-wall-tape-measure-metal-scissors-preparing-profiles-installation-wall-ceiling-frame_166373-1902.jpg",
            },
            {
              title: "Landscape Edge Perfection",
              tags: [
                "Details",
                "Polished",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/exotic-wildflower-bloom_23-2147835044.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
