/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

const primaryButton = {
  text: "Apply for Home Care Club",
  href: "#contact"
};
const secondaryButton = {
  text: "Our 32-Point Process",
  href: "#process"
};
const leftItems = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/romantic-villa-ephrussie-french-riviera-beauty-nature_1268-36319.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/photo-wood-texture-pattern_58702-13119.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/building-pattern_1203-3097.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/young-woman-sitting-cement-seat-urban-park_23-2148328851.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/front-view-city-architecture_23-2148798692.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/outdoor-portrait-caucasian-woman-classic-jumpsuit-with-red-lipstick-vacation-outside-villa-hotel_343596-438.jpg"
  }
];
const rightItems = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/billboard-template-urban-environment_23-2148197226.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/relaxed-couple-kissing_1153-957.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-roses-white-cage_23-2148229300.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-white-marble-textured-wall_53876-146222.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/house-with-marble-fence_1137-55.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/new-york-city-ny-usa-october-20-2020-vessel-hudson-yards-staircase-designed-by-architect-thomas-heatherwick-midtown-manhattan-west_1321-2483.jpg"
  }
];

type HeroSplitVerticalMarqueeProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  leftItems: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  rightItems: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HeroInline = () => {
  const duplicatedLeft = [...leftItems, ...leftItems, ...leftItems, ...leftItems];
  const duplicatedRight = [...rightItems, ...rightItems, ...rightItems, ...rightItems];

  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
  <section aria-label="Hero section" className="relative flex items-center min-h-[85vh] py-20 md:py-28 bg-background">
    <div className="flex flex-col md:flex-row items-center gap-12 md:gap-16 w-content-width mx-auto">
      <div className="w-full md:w-1/2 z-10">
        <div className="flex flex-col items-center md:items-start gap-4">
          <div className="px-3.5 py-1.5 text-xs md:text-sm uppercase tracking-wider font-semibold border border-[#a57d30] text-[#02066f] rounded-full w-fit bg-[#f1ece4]">
            <p>The 32-Point Standard</p>
          </div>

          <TextAnimation
            text="Your Home, Perfectly Maintained Year-Round."
            variant="fade-blur"
            gradientText={false}
            tag="h1"
            className="text-5xl md:text-6xl lg:text-7xl leading-[1.1] font-bold text-center md:text-left text-[#02066f] tracking-tight"
          />

          <TextAnimation
            text="Premium exterior home care for discerning homeowners in East Broward. We handle the details so you enjoy the prestige of a pristine home—stress & worry free."
            variant="fade-blur"
            gradientText={false}
            tag="p"
            className="md:max-w-[90%] text-lg md:text-xl leading-relaxed text-center md:text-left text-[#02066f]/80"
          />

          <div className="flex flex-wrap max-md:justify-center gap-4 mt-2">
            <Button text="Apply for Home Care Club" href="#contact" variant="primary" />
            <Button text="Our 32-Point Process" href="#process" variant="secondary" animationDelay={0.1} />
          </div>
        </div>
      </div>

      <div className="w-full md:w-1/2 h-[380px] md:h-[540px] rounded-2xl overflow-hidden shadow-2xl relative border border-[#a57d30]/30 group">
        <ImageOrVideo
          imageSrc="https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1600&q=80"
          className="w-full h-full object-cover rounded-2xl transition-transform duration-700 group-hover:scale-105"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-[#02066f]/30 via-transparent to-transparent pointer-events-none rounded-2xl" />
      </div>
    </div>
  </section>
</div>
  );
}
