// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "process" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProcessSection(): React.JSX.Element {
  return (
    <div id="process" data-section="process">
        <SectionErrorBoundary name="process">
              <FeaturesRevealCardsBento
          tag=""
          title=""
          description=""
          items={[
            {
              title: "",
              description: "",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/slate-background-texture-with-copy-space_23-2148283306.jpg",
            },
            {
              title: "Gutter Flow",
              description: "Clear and verified drainage paths.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/buildings-around_1127-2870.jpg",
            },
            {
              title: "Wall Finishes",
              description: "Assessment of stucco and siding integrity.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/teenage-boy-holding-book-hand-walking-front-university-building_23-2148093393.jpg",
            },
            {
              title: "Windows & Screens",
              description: "Deep clean and frame inspection.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/photo-metal-texture-pattern_58702-13853.jpg",
            },
            {
              title: "Entryways",
              description: "Detailed care of thresholds and doors.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-building-with-glass-windows-staircases-lights_181624-12044.jpg",
            },
            {
              title: "Patio Surfaces",
              description: "Deep clean for outdoor longevity.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-green-plant-stones_23-2148394728.jpg",
            },
            {
              title: "Final Walkthrough",
              description: "Final check against our 32-point list.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-white-house-with-welcoming-front-porch_23-2151974389.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
