// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProofSection(): React.JSX.Element {
  return (
    <div id="proof" data-section="proof">
        <SectionErrorBoundary name="proof">
              <SocialProofMarquee
          tag="Trusted in the Community"
          title="Our Standards Meet Luxury Demands"
          names={[
            "East Broward Estates",
            "Las Olas Luxury Homes",
            "Pompano Premier Living",
            "Fort Lauderdale Elite",
            "South Florida Residential Association",
            "Luxury Home Care Guild",
            "Coastal Property Experts",
          ]}
          textAnimation="fade"
          description="Description"
        />
        </SectionErrorBoundary>
      </div>
  );
}
