// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Voices of Value"
          title="What Homeowners Say"
          testimonials={[
            {
              name: "Sarah J.",
              role: "Resident",
              company: "East Broward",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/girl-posing-with-smarphone_23-2148124537.jpg",
            },
            {
              name: "Michael T.",
              role: "Homeowner",
              company: "Las Olas",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/stylish-young-couple-sitting-patio-drinking-red-wine_23-2147891238.jpg",
            },
            {
              name: "Emily R.",
              role: "Client",
              company: "Fort Lauderdale",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/charming-female-employee-helping-out-coworker-sitting-discussing-project-office-lounge-zone-lying-sofa-typing-keyboard-laptop-smiling-camera-amused-talking-freelancing-coworking-space_197531-30350.jpg",
            },
            {
              name: "David K.",
              role: "Member",
              company: "Pompano Beach",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-businessman-sitting-sofa-waiting-area_107420-95816.jpg",
            },
            {
              name: "Susan P.",
              role: "Homeowner",
              company: "South Florida",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/sweet-kiss-happy-couple-is-standing-near-new-car-house-with-cardboard-boxes_496169-286.jpg",
            },
          ]}
          textAnimation="slide-up"
          description="Description"
        />
        </SectionErrorBoundary>
      </div>
  );
}
